apiVersion: v1
kind: Service
metadata:
  name: nginx-service
#  annotations:
#    prometheus.io/scrape: 'true'
  labels:
    app: nginx
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP
  selector:
    app: nginx
  type: NodePort