apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;
    events {
      worker_connections  1024;
    }
    http {
      server {
          listen       80;
          server_name  server;
          location = /basic_status {
            stub_status;
          }
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            keepalive_timeout 65s;
          }
      }
    }