apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx-service
spec:
  ports:
    - name: http-web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: metrics
      port: 9113
      targetPort: 9113
      protocol: TCP
  selector:
    app: nginx
  type: ClusterIP