apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  labels:
    team: sre
spec:
  selector:
    matchLabels:
      app: nginx-service
  endpoints:
  - port: web
    path: /basic_status
    scheme: http
    scrapeTimeout: 10s
  jobLabel: myjob-nginx
  namespaceSelector:
    matchNames:
    - default