apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-nginx-server
        image: nginx:1.21.6
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/
        ports:
        - name: web
          containerPort: 80
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args: ['-nginx.scrape-uri', 'http://127.0.0.1:80/basic_status']
        ports:
        - name: metrics
          containerPort: 9113
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config