apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: paymentservice
        image: proreg92/otus_task3_paymentsvc:2.0  # image: proreg92/otus_task3_paymentsvc:2.0
        
        env:
        - name: PORT
          value: "50051"
        - name: GCLOUD_PROJECT
          value: "123218358777"
              