apiVersion: v1
kind: Pod
metadata:
  name: minioclient
  # Note that the Pod does not need to be in the same namespace as the loader.
  labels:
    app: minioclient
spec:
  containers:
  - name: minio
    image: ibmcom/minio-mc:RELEASE.2019-04-03T17-59-57Z.1
    env:   
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secrets
          key: MINIO_ACCESS_KEY
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: minio-secrets
          key: MINIO_SECRET_KEY
    imagePullPolicy: IfNotPresent
    command: ["/test/test-minio.sh"]
    volumeMounts:
      - name: test-minio
        mountPath: "/test"
  volumes:
    - name: test-minio
      configMap:
        name: test-minio
        defaultMode: 0745
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-minio
data:
  test-minio.sh: |
    #!/bin/sh
    # If TLS is not enabled use the following URL:
    mc config host add myminio http://10.244.0.7:9000 $MINIO_ACCESS_KEY  $MINIO_SECRET_KEY S3v4
    # If TLS is enabled for minio service, use the following URL. If certificate is self signed user --insecure
    # mc config host add myminio https://<Minio Service Name>:9000 <ACCESSKEY>  <SECRETKEY> S3v4 --insecure
    sleep 3600