apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: avtandilko/hipster-frontend:v0.0.1 #  - <-- error here and also in ENV global variables from Deployment manifest
  #- image: proreg92/otus_task2_hipster:1.0
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never

